import React from 'react';

export default function Index(){
    return(
        <>
            <h1>Teste</h1>
            <h1>Teste</h1>
            <h1>Teste</h1>
            <h1>Teste</h1>
            <h1>Teste</h1>
            <h1>Teste</h1>
            <h1>Teste</h1>
            <h1>Teste</h1>
            <h1>Teste</h1>
            <h1>Teste</h1>
            <h1>Teste</h1>
            <h1>Teste</h1>
            <h1>Teste</h1>
            <h1>Teste</h1>
            <h1>Teste</h1>
            <h1>Teste</h1>
            <h1>Teste</h1>
            <h1>Teste</h1>
            <h1>Teste</h1>
            <h1>Teste</h1>
            <h1>Teste</h1>
            <h1>Teste</h1>
            <h1>Teste</h1>
            <h1>Teste</h1>
            <h1>Teste</h1>
            <h1>Teste</h1>
            <h1>Teste</h1>
            <h1>Teste</h1>
            <h1>Teste</h1>
            <h1>Teste</h1>
            <h1>Teste</h1>
            <h1>Teste</h1>
            <h1>Teste</h1>
            <h1>Teste</h1>
            <h1>Teste</h1>
            <h1>Teste</h1>
            <h1>Teste</h1>
            <h1>Teste</h1>
        </>
    );
};